### ISSUE TITLE
similar to glob2base

### ISSUE THREAD

**Issue by contra** [es128/glob-parent#1]
lets merge these two http://github.com/wearefractal/glob2base

do you see any features glob2base doesnt support?

**Comment by es128** [comment]
I didn't find glob2base when I was looking. But I don't want to add `glob` as a dependency to be able to do this. Why do you require use of a `Glob` object?

Also, mine does it with a lot less code :wink:

If you'd be willing to adopt this more stripped down approach, at least as an option (i.e. allow either plain strings or `Glob` object as input), then we could merge.

**Comment by contra** [comment]
@es128 Because the case I was covering we already have a glob instance, so there is no reason to parse it twice. If the performance is better to just re-parse it (it probably is) then I will just deprecate mine and switch to this one.

**Comment by tunnckoCore** [comment]
@contra just because yours is on top of node-glob and minimatch family.

actually I also create same package and it looks like in same time as es128, haha
https://github.com/tunnckoCore/glob2fp
