### ISSUE TITLE
enable appveyor

### ISSUE THREAD

**Issue by phated** [es128/glob-parent#9]
Seems there's some problems on Windows.

**Comment by es128** [comment]
Done, but no failures in appveyor. Can you link to the issue report you're referring to?

**Comment by phated** [comment]
@es128 it was in reference to https://github.com/es128/glob-parent/pull/7#discussion_r83573103 - maybe @jonschlinkert can trigger a new build

**Comment by es128** [comment]
https://ci.appveyor.com/project/es128/glob-parent/build/1.0.5
